variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - deploy

before_script:
  - git submodule update --init
  
cpp_lint:
  stage: lint
  image: registry.gitlab.com/ai-r/cogment-build-env:50609b20f26403391631ba91c3d734f71499f4e3
  script:
    - cmake .
    - make format
    - git diff --exit-code

build:
  stage: build
  image: registry.gitlab.com/ai-r/cogment-build-env:50609b20f26403391631ba91c3d734f71499f4e3
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

deploy:
  stage: deploy
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:19.03.1-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

release:
  stage: deploy
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:19.03.1-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags