variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - deploy

before_script:
  - git submodule update --init

cpp_lint:
  stage: lint
  image: registry.gitlab.com/ai-r/cogment-build-env:bce25673a3e81ea03ab0723dac67d374aa584d97
  script:
    - cmake .
    - make format
    - git diff --exit-code

build:
  stage: build
  image: registry.gitlab.com/ai-r/cogment-build-env:bce25673a3e81ea03ab0723dac67d374aa584d97
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
