image: docker:19.03.1

stages:
  - lint
  - build
  - publish

lint:
  stage: lint
  image: golang:1.13
  script:
    - make lint

services:
  - docker:19.03.1-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build_binaries:
  stage: build
  needs: []
  image: golang:1.13
  script:
    - apt-get update -y
    - apt-get install -y protobuf-compiler
    - make release
  artifacts:
    expire_in: 1 week
    paths:
      - build

build_docker_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest .
  except:
    - develop

# INTERNAL AI-R HELPER - Publish the current version from the `develop` branch with the `latest` docker tag.
publish_latest_docker_image:
  stage: publish
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - develop

publish_tagged_docker_image:
  stage: publish
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag cogment/cli:$CI_COMMIT_TAG .
    - docker push cogment/cli:$CI_COMMIT_TAG
  only:
    - tags

publish_binaries_to_gh_release:
  stage: publish
  needs: ["build_binaries"]
  image: ubuntu:focal
  script:
    - apt update -y
    - apt-get install -y gnupg2 software-properties-common
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
    - apt-add-repository https://cli.github.com/packages
    - apt update -y
    - apt install gh -y
    - gh auth login --with-token < $GH_TOKEN
    - gh release create $CI_COMMIT_TAG ./build/* -t $CI_COMMIT_TAG -R cogment/cogment-cli
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(?:-[[:alnum:]]+)?$/
