stages:
  - lint
  - build
  - deploy

.use_build_env:
  image: cogment/orchestrator-build-env:v1.0.0
  before_script:
    - mkdir build
    - cd build
    - cmake ..

cpp_lint:
  extends: .use_build_env
  stage: lint
  script:
    - make format
    - git diff --exit-code

build:
  extends: .use_build_env
  stage: build
  script:
    - make
