run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m

  skip-dirs:
    - .go

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - revive


