license:
  copyright_year: 2023
  author: "AI Redefined Inc. <dev+cogment@ai-r.com>"
  ignore:
    - "build"
    - "install"
    - "packages/orchestrator_dependencies"
    - "packages/orchestrator/lib/cogment/base64.cpp"
    - "packages/orchestrator/third_party"
    - "packages/orchestrator/build"
    - "packages/orchestrator/install"
    - "packages/cli/grpcapi"
    - "packages/cli/testdata"
    - "packages/cli/pkged.go"
    - "packages/cli/**/.snapshots"
