# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='testit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x06testit\"\x0b\n\tEnvConfig\"4\n\x0bTrialConfig\x12%\n\nenv_config\x18\x01 \x01(\x0b\x32\x11.testit.EnvConfig\"\r\n\x0bObservation\"\x0e\n\x0cMasterAction\"\r\n\x0bSmartAction\"\x0c\n\nDumbActionb\x06proto3'
)




_ENVCONFIG = _descriptor.Descriptor(
  name='EnvConfig',
  full_name='testit.EnvConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=33,
)


_TRIALCONFIG = _descriptor.Descriptor(
  name='TrialConfig',
  full_name='testit.TrialConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='env_config', full_name='testit.TrialConfig.env_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=87,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='testit.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=102,
)


_MASTERACTION = _descriptor.Descriptor(
  name='MasterAction',
  full_name='testit.MasterAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=118,
)


_SMARTACTION = _descriptor.Descriptor(
  name='SmartAction',
  full_name='testit.SmartAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=133,
)


_DUMBACTION = _descriptor.Descriptor(
  name='DumbAction',
  full_name='testit.DumbAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=147,
)

_TRIALCONFIG.fields_by_name['env_config'].message_type = _ENVCONFIG
DESCRIPTOR.message_types_by_name['EnvConfig'] = _ENVCONFIG
DESCRIPTOR.message_types_by_name['TrialConfig'] = _TRIALCONFIG
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['MasterAction'] = _MASTERACTION
DESCRIPTOR.message_types_by_name['SmartAction'] = _SMARTACTION
DESCRIPTOR.message_types_by_name['DumbAction'] = _DUMBACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvConfig = _reflection.GeneratedProtocolMessageType('EnvConfig', (_message.Message,), {
  'DESCRIPTOR' : _ENVCONFIG,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:testit.EnvConfig)
  })
_sym_db.RegisterMessage(EnvConfig)

TrialConfig = _reflection.GeneratedProtocolMessageType('TrialConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRIALCONFIG,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:testit.TrialConfig)
  })
_sym_db.RegisterMessage(TrialConfig)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:testit.Observation)
  })
_sym_db.RegisterMessage(Observation)

MasterAction = _reflection.GeneratedProtocolMessageType('MasterAction', (_message.Message,), {
  'DESCRIPTOR' : _MASTERACTION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:testit.MasterAction)
  })
_sym_db.RegisterMessage(MasterAction)

SmartAction = _reflection.GeneratedProtocolMessageType('SmartAction', (_message.Message,), {
  'DESCRIPTOR' : _SMARTACTION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:testit.SmartAction)
  })
_sym_db.RegisterMessage(SmartAction)

DumbAction = _reflection.GeneratedProtocolMessageType('DumbAction', (_message.Message,), {
  'DESCRIPTOR' : _DUMBACTION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:testit.DumbAction)
  })
_sym_db.RegisterMessage(DumbAction)


# @@protoc_insertion_point(module_scope)

